# Generated by Django 3.2.19 on 2023-05-23 15:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=64, null=True, verbose_name='User Name')),
                ('first_name', models.CharField(max_length=256, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название салона')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес салона')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя мастера')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Контактный номер мастера')),
                ('procedure', models.ManyToManyField(related_name='procedures', to='bot.Procedures', verbose_name='Услуга, предоставляемая мастером')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='masters', to='bot.salons', verbose_name='Салон работы мастера')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(verbose_name='Дата и время записи на услугу')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_appointments', to='bot.clients', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='master_appointments', to='bot.masters', verbose_name='Мастер')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_appointments', to='bot.procedures', verbose_name='Запись на услугу')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salon_appoinments', to='bot.salons', verbose_name='Салон')),
            ],
        ),
    ]
