# Generated by Django 3.2.19 on 2023-05-23 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20230523_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='salon',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 23, 22, 41, 40, 381241), verbose_name='Дата записи на услугу'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 23, 22, 41, 40, 381240), verbose_name='Время записи на услугу'),
        ),
    ]
