# Generated by Django 4.2.1 on 2023-05-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_weekend_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="telegram_id",
            field=models.IntegerField(),
        ),
    ]
