# Generated by Django 3.2.19 on 2023-05-23 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20230523_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 23, 22, 56, 17, 584450), verbose_name='Дата записи на услугу'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 23, 22, 56, 17, 584450), verbose_name='Время записи на услугу'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure_appointments', to='bot.procedures', verbose_name='Запись на услугу'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='procedure',
            field=models.ManyToManyField(related_name='masters', to='bot.Procedures', verbose_name='Услуга, предоставляемая мастером'),
        ),
    ]
