# Generated by Django 4.2.1 on 2023-05-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_appointments_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание О Нас"
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon_about",
                        to="bot.salons",
                        verbose_name="Салон",
                    ),
                ),
            ],
        ),
    ]
