# Generated by Django 3.2.19 on 2023-05-23 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20230523_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 23, 23, 3, 18, 742936), verbose_name='Дата записи на услугу'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 23, 23, 3, 18, 742935), verbose_name='Время записи на услугу'),
        ),
    ]
