# Generated by Django 4.2.1 on 2023-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_aboutus"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Стартовый текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "Стартовый текст",
                "verbose_name_plural": "Стартовые текста",
            },
        ),
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "О Нас", "verbose_name_plural": "О Нас"},
        ),
    ]
