# Generated by Django 3.2.19 on 2023-05-26 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20230526_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='fry',
            field=models.BooleanField(blank=True, default=True, verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='masters',
            name='mon',
            field=models.BooleanField(blank=True, default=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='masters',
            name='sun',
            field=models.BooleanField(blank=True, default=True, verbose_name='Воскресенье'),
        ),
        migrations.AddField(
            model_name='masters',
            name='sut',
            field=models.BooleanField(blank=True, default=True, verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='masters',
            name='thu',
            field=models.BooleanField(blank=True, default=True, verbose_name='Черверг'),
        ),
        migrations.AddField(
            model_name='masters',
            name='tue',
            field=models.BooleanField(blank=True, default=True, verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='masters',
            name='wed',
            field=models.BooleanField(blank=True, default=True, verbose_name='Среда'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 14, 3, 9, 22843), verbose_name='Дата записи на услугу'),
        ),
    ]
