# Generated by Django 4.2.1 on 2023-05-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_starttext_alter_aboutus_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.IntegerField(unique=True)),
                (
                    "name",
                    models.CharField(max_length=256, null=True, verbose_name="Name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.RemoveField(
            model_name="appointments",
            name="name",
        ),
        migrations.RemoveField(
            model_name="appointments",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="appointments",
            name="telegram_id",
        ),
        migrations.AddField(
            model_name="appointments",
            name="client",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appoinments",
                to="bot.client",
                verbose_name="Клиент",
            ),
            preserve_default=False,
        ),
    ]
